### ISSUE TITLE
Solution for anyBoggle too difficult to read

### ISSUE THREAD

**Issue by neugierige** [ga-wdi-boston/js-boggle-challenge#56]
this 1-line solution, although clever, is very difficult to read, especially for students in their 1st week

```
const anyBoggle = (rank, tray, coords) =>
  coords.map(c => tray[c[0] * rank + c[1]]).join('');
```

**Comment by gaand** [comment]
@neugierige I disagree.  Solutions aren't necessarily meant to be obvious.  And solutions similar to this have been created by developers in previous cohorts.
